# Generated by Django 4.1.7 on 2023-03-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturesGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('edible', models.CharField(max_length=1000)),
                ('origin', models.CharField(max_length=1000)),
                ('benefits', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
